---
- name: Converge
  hosts: all
  become: true

  vars:
    apache_listen_ip: "127.0.0.1"
    apache_listen_port: 81
    apache_mods_enabled:
      - access_compat.load # Allow, Deny directives
      - authz_core.load # Require directive
      - authz_host.load # Authz provider: local
      - dir.conf
      - dir.load # DirectoryIndex
      - mpm_event.conf
      - mpm_event.load # No MPM loaded
      - proxy.load # For proxy_fcgi
      - proxy_fcgi.load # PHP-FPM
      - remoteip.load # Real IP from nginx
      - rewrite.load # SEF
      - status.load # Monitoring
    apache_mods_disabled:
      - alias.conf
      - alias.load
      - auth_basic.load
      - authn_core.load
      - authn_file.load
      - authz_user.load
      - autoindex.conf
      - autoindex.load
      - deflate.conf
      - deflate.load
      - env.load
      - filter.load
      - mime.conf
      - mime.load
      - negotiation.conf
      - negotiation.load
      - setenvif.conf
      - setenvif.load

    apache_create_vhosts: false
    apache_vhosts_filename: "vhosts.conf"
    apache_vhosts:
      - servername: "example.com"
        documentroot: "/var/www/vhosts/example.com"
      - servername: "subdomain.example.com"
        documentroot: "/var/www/vhosts/subdomain.example.com"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: ansible-role-apache
